#!/usr/bin/ruby
# Defines event types that are sent from the wave server.
#
# This module defines all of the event types currently supported by the wave
# server.

# Event Types
WAVELET_BLIP_CREATED = 'WAVELET_BLIP_CREATED'
WAVELET_BLIP_REMOVED = 'WAVELET_BLIP_REMOVED'
WAVELET_PARTICIPANTS_CHANGED = 'WAVELET_PARTICIPANTS_CHANGED'
WAVELET_SELF_ADDED = 'WAVELET_SELF_ADDED'
WAVELET_SELF_REMOVED = 'WAVELET_SELF_REMOVED'
WAVELET_TIMESTAMP_CHANGED = 'WAVELET_TIMESTAMP_CHANGED'
WAVELET_TITLE_CHANGED = 'WAVELET_TITLE_CHANGED'
WAVELET_VERSION_CHANGED = 'WAVELET_VERSION_CHANGED'
BLIP_CONTRIBUTORS_CHANGED = 'BLIP_CONTRIBUTORS_CHANGED'
BLIP_DELETED = 'BLIP_DELETED'
BLIP_SUBMITTED = 'BLIP_SUBMITTED'
BLIP_TIMESTAMP_CHANGED = 'BLIP_TIMESTAMP_CHANGED'
BLIP_VERSION_CHANGED = 'BLIP_VERSION_CHANGED'
DOCUMENT_CHANGED = 'DOCUMENT_CHANGED'
FORM_BUTTON_CLICKED = 'FORM_BUTTON_CLICKED'

# Event Properties

# Properties for WAVELET_PARTICIPANTS_CHANGED, WAVELET_SELF_ADDED and
# WAVELET_SELF_REMOVED
PARTICIPANTS_ADDED = 'participantsAdded'
PARTICIPANTS_REMOVED = 'participantsRemoved'

# Properties for WAVELET_TITLE_CHANGED
TITLE = 'title'

# Properties for WAVELET_VERSION_CHANGED
VERSION = 'version'
